# Generated by Django 4.2.5 on 2025-10-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_train', '0005_tag_entry_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorprofile',
            options={'verbose_name': 'Профиль автора', 'verbose_name_plural': 'Профили авторов'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
